'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SkinEditor.Plugin.Editor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _goto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_goto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;LexScheme xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        '''  &lt;Author&gt;Quantum Whale&lt;/Author&gt;
        '''  &lt;Name&gt;CSS language&lt;/Name&gt;
        '''  &lt;Desc&gt;Syntax Scheme for Cascading Style Sheets Language&lt;/Desc&gt;
        '''  &lt;Copyright&gt;Copyright Quantum Whale, 2003&lt;/Copyright&gt;
        '''  &lt;FileExtension&gt;.css&lt;/FileExtension&gt;
        '''  &lt;FileType&gt;css&lt;/FileType&gt;
        '''  &lt;Version&gt;1.1&lt;/Version&gt;
        '''  &lt;Styles&gt;
        '''    &lt;Style&gt;
        '''      &lt;Name&gt;idents&lt;/Name&gt;
        '''      &lt;ForeColor&gt;Brown&lt;/ForeCo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Css() As String
            Get
                Return ResourceManager.GetString("Css", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;LexScheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;Author&gt;Quantum Whale&lt;/Author&gt;
        '''  &lt;Name&gt;ASP, VB, Java, PHP Scripts in HTML&lt;/Name&gt;
        '''  &lt;Desc&gt;Syntax Scheme for ASP, VB, PHP, Java Scripts in HTML Language&lt;/Desc&gt;
        '''  &lt;Copyright&gt;Copyright Quantum Whale, 2003&lt;/Copyright&gt;
        '''  &lt;FileExtension&gt;.html;.htm;.asp;.php&lt;/FileExtension&gt;
        '''  &lt;FileType&gt;html(scripts)&lt;/FileType&gt;
        '''  &lt;Version&gt;1.1&lt;/Version&gt;
        '''  &lt;Styles&gt;
        '''    &lt;Style [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Html() As String
            Get
                Return ResourceManager.GetString("Html", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;LexScheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;Author&gt;Quantum Whale&lt;/Author&gt;
        '''  &lt;Name&gt;Java script language&lt;/Name&gt;
        '''  &lt;Desc&gt;Syntax Scheme for Java Script Language&lt;/Desc&gt;
        '''  &lt;Copyright&gt;Copyright Quantum Whale, 2003&lt;/Copyright&gt;
        '''  &lt;FileExtension&gt;.js&lt;/FileExtension&gt;
        '''  &lt;FileType&gt;javascript&lt;/FileType&gt;
        '''  &lt;Version&gt;1.1&lt;/Version&gt;
        '''  &lt;Styles&gt;
        '''    &lt;Style&gt;
        '''      &lt;Name&gt;idents&lt;/Name&gt;
        '''      &lt;ForeColor&gt;ControlTex [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Javascript() As String
            Get
                Return ResourceManager.GetString("Javascript", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property print_preview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("print_preview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer_options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer_options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;LexScheme xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;Author&gt;Quantum Whale&lt;/Author&gt;
        '''  &lt;Name&gt;Python language&lt;/Name&gt;
        '''  &lt;Desc&gt;Syntax Scheme for Python Language&lt;/Desc&gt;
        '''  &lt;Copyright&gt;Copyright Quantum Whale, 2003&lt;/Copyright&gt;
        '''  &lt;FileExtension&gt;.py&lt;/FileExtension&gt;
        '''  &lt;FileType&gt;python&lt;/FileType&gt;
        '''  &lt;Version&gt;1.1&lt;/Version&gt;
        '''  &lt;Styles&gt;
        '''    &lt;Style&gt;
        '''      &lt;Name&gt;idents&lt;/Name&gt;
        '''      &lt;ForeColor&gt;ControlText&lt;/ForeColor&gt;        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Python() As String
            Get
                Return ResourceManager.GetString("Python", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property replace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("replace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
